services:
  dm:
    build: 
      context: ./leshanDemoServer
      dockerfile: Dockerfile.leshan-server
   
    ports:
      - "8080"
      - "5783:5683/udp"

  bs:
    build: 
      context: ./bootstrapServer
      dockerfile: Dockerfile.leshan-bsserver
 
    ports:
      - "8080"
      - "5683:5683/udp"
      - "5684:5684/udp"

  encore:
    image: encore-leshan-demo:2.0.0
    ports:
      - "8080:8080"
    depends_on:
      - dm
      - bs
    env_file:
      - .env
    command: ["encore", "run"]

  nginx:
    image: nginx:alpine
    ports:
       - "80:80"            
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - dm
      - bs
      - encore
